version: "2"

services:    
    master:
      image: anantpukale/spark_env:1.0
      command: opt/spark/bin/spark-class org.apache.spark.deploy.master.Master -h master
      hostname: master
      environment:
        MASTER: spark://master:7077
        SPARK_CONF_DIR: opt/spark/conf
        SPARK_PUBLIC_DNS: localhost
      expose:
        - 7001
        - 7002
        - 7003
        - 7004
        - 7005
        - 7006
        - 7077
        - 6066
      ports:
        - 4040:4040
        - 6066:6066
        - 7077:7077
        - 8080:8080
        
      volumes:
        - ./conf/master:/conf
        - ./data:/tmp/data

    worker:
      image: anantpukale/spark_env:1.0
      command: opt/spark/bin/spark-class org.apache.spark.deploy.worker.Worker spark://master:7077
      hostname: worker
      environment:
        SPARK_CONF_DIR: opt/spark/conf
        SPARK_WORKER_CORES: 2
        SPARK_WORKER_MEMORY: 1g
        SPARK_WORKER_PORT: 8881
        SPARK_WORKER_WEBUI_PORT: 8081
        SPARK_PUBLIC_DNS: localhost
      links:
        - master
      expose:
        - 7012
        - 7013
        - 7014
        - 7015
        - 7016
        - 8881
      ports:
        - 8081:8081
      volumes:
        - ./conf/worker:/conf
        - ./data:/tmp/data
    rest:
      image: anantpukale/spark_app:1.0
      command: opt/spark/bin/spark-submit --class com.example.demo.DemoApplication --master spark://master:7077 demo-0.0.1-SNAPSHOT-shaded.jar
      #command: /start-worker
      hostname: rest
      environment:
        SPARK_CONF_DIR: opt/spark/conf
        SPARK_WORKER_CORES: 1
        SPARK_WORKER_MEMORY: 1g
        SPARK_WORKER_PORT: 8882
        SPARK_WORKER_WEBUI_PORT: 8083
        SPARK_PUBLIC_DNS: localhost
      links:
        - master
      expose:
        - 7017
        - 7018
        - 7019
        - 7020
        - 7021
        - 8882
      ports:
        - 8082:8082
      volumes:
        - ./conf/rest:/conf
        - ./data:/tmp/data    